// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("Octokit")]
[assembly: AssemblyVersionAttribute(Octokit.VersionConsts.Version)]
[assembly: AssemblyFileVersionAttribute(Octokit.VersionConsts.Version)]
[assembly: ComVisibleAttribute(false)]

namespace Octokit { static class VersionConsts { internal const string Version = "0.23.0.2"; } }
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = Octokit.VersionConsts.Version + "-ghu";
        internal const string InformationalVersion = Octokit.VersionConsts.Version + "-ghu";
    }
}
