// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("Octokit")]
[assembly: AssemblyVersionAttribute(Consts.LibraryVersion)]
[assembly: AssemblyFileVersionAttribute(Consts.LibraryVersion)]
[assembly: ComVisibleAttribute(false)]

static class Consts { internal const string LibraryVersion = "0.24.0.1"; }

namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const string Version = Consts.LibraryVersion;
        internal const string InformationalVersion = Consts.LibraryVersion + "-gfu";
    }
}
