// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("Octokit")]
[assembly: AssemblyVersionAttribute("0.23.0.1")]
[assembly: AssemblyFileVersionAttribute("0.23.0.1")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.23.0.1-ghu";
        internal const string InformationalVersion = "0.23.0.1-ghu";
    }
}
